services:
  db:
    image: postgres:16
    container_name: math_container_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: math_db
    volumes:
      - pg_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: math_container_app
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      DATABASE_URL: postgresql://user:123@db:5432/math_db
    command: ["./wait-for-it.sh", "db", "5432", "python", "main.py"]


volumes:
  pg_data:
