services:
  db:
    image: postgres:16
    container_name: math_container_db
    restart: always
    ports:
      - "15432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2s
      timeout: 3s
      retries: 15

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: math_container_app
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:5000"
    volumes:
      - .:/app
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/postgres
    #command: ["sh", "-c", "chmod +x wait-for-it.sh && ./wait-for-it.sh db 5432 python main.py"]

volumes:
  pg_data:
